version: "3.7"

services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  redis:
    image: redis
    container_name: redis
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    restart: always

  flask:
    build: ./flask
    container_name: flask
    restart: always
