version: "3.7"

services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  flask:
    build: ./flask
    container_name: flask
    restart: always
    ports:
      - "3030:3030"
    # expose 3000 to test uwsgi is serving
    expose:
      - "3030"
